### ISSUE TITLE
abnormal measurements

### ISSUE THREAD

**Issue by matigumma** [Seeed-Studio/Seeed_Arduino_MultiGas#2]
**Describe the bug**
high values on measurements

im using:
nodemcu v1.0 (cp2102)

grove multi sensor v2

code:
```
#include <Multichannel_Gas_GMXXX.h>
#include <Wire.h>

GAS_GMXXX<TwoWire> gas;

unsigned int no2, c2h5ch, voc, co;

void setup() {

  Serial.begin(115200);
  gas.begin(Wire, 0x08);

}
void loop() {

//VOC
  voc = gas.getGM502B();
  Serial.print("VOC: ");
  Serial.print(voc);
  Serial.print(" ppm");Serial.print("  =  ");Serial.print(gas.calcVol(voc)); Serial.println("V");
  //CO
  co = gas.getGM702B();
  if (co > 999) co = 999;
  Serial.print("CO: ");
  Serial.print(co);
  Serial.print(" ppm");Serial.print("  =  ");Serial.print(gas.calcVol(co)); Serial.println("V");
  
  //NO2
  no2 = gas.getGM102B();
  if (no2 > 999) no2 = 999;
  Serial.print("NO2: ");
  Serial.print(no2);
  Serial.print(" ppm");Serial.print("  =  ");Serial.print(gas.calcVol(no2)); Serial.println("V");

  //C2H5CH
  c2h5ch = gas.getGM302B();
  if (c2h5ch > 999) c2h5ch = 999;
  Serial.print("C2H5CH: ");
  Serial.print(c2h5ch);
  Serial.print(" ppm");Serial.print("  =  ");Serial.print(gas.calcVol(c2h5ch)); Serial.println("V");

  Serial.println("----------------------------------------------------------------");
  delay(2000);
}
```

and i getting this as result :img attached
<img width="892" alt="Screen Shot 2020-12-12 at 23 56 14" src="https://user-images.githubusercontent.com/794606/102001893-c3772c80-3cd5-11eb-9794-fcc6965bd7d7.png">

**Comment by Pillar1989** [comment]
@matigumma I don't see exaggerated anomalous data.

**Comment by nor2101** [comment]
@matigumma those are not ppm. The value returned for all gases is in raw adc points, which for some reason are named as "eq" in the example files. If you need ppm values you need to calculate them yourself from the raw adc values.

**Comment by moemuses** [comment]
@Pillar1989  @nor2101 Can you please explain more how we can calculate ppm from "eq" ?

**Comment by lakshanthad** [comment]
@matigumma 

Please follow this:
https://github.com/Seeed-Studio/Seeed_Arduino_MultiGas/issues/5
